# Generated by Django 2.2 on 2019-04-25 05:58

import apps.user_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20190425_0528'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.user_app.models.UserManager()),
            ],
        ),
    ]
