# Generated by Django 2.2 on 2019-04-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0004_auto_20190425_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nick_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='single',
            field=models.BooleanField(null=True),
        ),
    ]
