# Generated by Django 2.2 on 2019-04-26 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_user_friend'),
        ('user_app', '0005_user_friends'),
    ]

    operations = [
    ]
