# Generated by Django 2.2 on 2019-04-28 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_merge_20190426_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friend',
        ),
    ]
